openapi: 3.0.0
info:
  title: AI Subscription Negotiator API
  version: "0.1.0"

paths:
  /users/{userId}/subscriptions:
    get:
      summary: List user subscriptions
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

  /subscriptions/{subscriptionId}/draft:
    post:
      summary: Generate a negotiation draft for a subscription
      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tone:
                  type: string
      responses:
        '201':
          description: Draft created

  /drafts/{draftId}/approve:
    post:
      summary: Approve and send a negotiation draft
      parameters:
        - in: path
          name: draftId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sent / Recorded
